### ISSUE TITLE
Resolve the ambiguity of the missing `Api-Version` header

### ISSUE THREAD

**Issue by malor** [xsnippet/xsnippet-api#41]
If the `Api-Version` header value is not passed explicitly, there are multiple options how the  API request could be handled:

1.  Forbid such HTTP requests and *require* the `Api-Version` header to be passed.

Pros:
- no ambiguity in the first place

Cons:
- requires passing a version value explicitly, even if clients do not really care (e.g. minor changes between versions or the version in question did not change this particular API endpoint)
- breaks existing API clients (if there are any :))

2. Treat the missing header value as if the *minimum* supported version was specified. 

Pros:
- deployment of new versions to production does not break the clients that do not specify the version value explicitly for each request

Cons:
- clients still break when the minimum supported API version is bumped on the server side (it's hard to come up with a *visible* deprecation mechanism - warnings in responses can easily be ignored as well as deprecation markers in the version list)

3. Treat the missing header value as if the *maximum* supported version was specified.

Pros:
- effectively forces the clients to follow the updates of the server code

Cons:
- every new deployment to production potentially breaks the existing clients that do not specify the version value explicitly for each request

We should choose the way how we want this to be solved and update the code / the OpenAPI spec accordingly.

**Comment by zoresvit** [comment]
Move fast and break things! © 👍 😃 

I vote for option 3.

Rationale
---------

I think every interface should aim to provide maximum functionality with minimum user effort (learning curve). So the less knowledge user needs to use the interface — the better. It also needs to be convenient and safe.

With option 1 the user has to have prior knowledge about required headers (steeper learning curve) and has to specify the header with every call (inconvenient, especially with `curl`/`httpie`). In such scenario the very first attempt of the user to use the API intuitively (`curl api.xsnippet.org`) is ending with an error instructing to specify the header. It's also guaranteed to be a breaking change for existing clients. Since it's inconvenient and breaking, seems like a lose-lose to me. This already excludes option 1.

We are left with options 2 and 3. Option 2 might seem as a viable choice to make the API safe, but if we look at it carefully — it's just a delayed version of option 3. Both 2 and 3 _might_ eventually break existing client, option 2 will just do it a bit later, so for *existing* users there's no much difference. However for new users option 2 has major disadvantage: by default it sends *new* users to an old API version. This deprives new users of benefits of new API version (new features, fixes, performance improvements), while doesn't provide much more stability to existing users (if there is a breaking change, it will still break clients, just later). So essentially option 2 just makes users to live in the past :)

Therefore I see option 3 as the best trade-off between convenience, safety and efficiency.

**Comment by malor** [comment]
Since #64 we have a default version explicitly set in the code.
